# Generated by Django 4.0.4 on 2022-05-27 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseapp', '0007_alter_post_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='snippet',
            field=models.CharField(default='This is a snippet', max_length=300),
        ),
    ]
