# Generated by Django 4.0.4 on 2022-05-29 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseapp', '0013_alter_profile_linkedin_url_alter_profile_twitter_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='twitter_url',
            field=models.CharField(blank=True, default='#', max_length=255, null=True),
        ),
    ]
